anon0mys/scavengr_rails_frontend

Gemfile, Gemfile.lock, PULL_REQUEST_TEMPLATE.md, app/controllers/home_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/services/django/users.rb, app/views/home/index.html.erb, app/views/users/new.html.erb, config/routes.rb, spec/features/users/user_can_create_account_spec.rb, spec/models/user_spec.rb, spec/services/django/users_spec.rb
* Creates User model, controller and create route
* Creates Django::Users service to handle requests to backend
=> User authentication

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/services/django/users.rb, app/views/home/index.html.erb, app/views/sessions/new.html.erb, app/views/users/new.html.erb, config/routes.rb, spec/features/users/user_can_create_account_spec.rb, spec/features/users/user_login_logout_spec.rb, spec/models/user_spec.rb, spec/services/django/users_spec.rb
* Update user creation service to interact with Django authentication requirements
* Add log in and log out paths and associated services
=> User login logout

app/assets/stylesheets/main.scss, app/views/scavenger_hunts/edit.html.erb
* Removed comments
* Increased height of scavenger hunt description text area
* Add padding to cancel button
=> Minor updates to styling

app/assets/stylesheets/index.scss, app/views/scavenger_hunts/index.html.erb, app/views/user_scavenger_hunts/index.html.erb, config/application.rb, public/packs/manifest.json, spec/features/scavenger_hunts/user_can_see_their_scavenger_hunts_spec.rb, spec/fixtures/json/user_scavenger_hunts.json
* Added cards to index
* Added buttons to cards for edit and delete
* Update card to be a link to show page
=> Index styling

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/map_setup.js, app/controllers/points_controller.rb, app/controllers/user_scavenger_hunts_controller.rb, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/models/point.rb, app/services/elastic_service.rb, app/views/points/new.html.erb, app/views/user_scavenger_hunts/show.html.erb, config/routes.rb, public/packs/manifest.json, spec/features/scavenger_hunts/user_can_see_one_of_their_scavenger_hunts_spec.rb, spec/features/scavenger_hunts/user_can_see_one_of_their_scavenger_hunts_spec0.rb
=> WIP Add points

app/channels/scavenger_hunt_channel.rb, app/services/elastic_service.rb
* Pushed user point creation logic to the elastic service
=> Moved user point creation method to elastic service

app/channels/scavenger_hunt_channel.rb, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/javascript/bundles/ScavengerHunt/services/scavengerHuntApi.js, app/javascript/bundles/ScavengerHunt/stores/ScavengerHuntStore.js, app/services/elastic_service.rb, lib/tasks/elastic_search_setup.rake, public/packs/manifest.json
- Updated rake task for user_points index. Revised ElasticSearchService#within_radius and #outside_radius to query user_points index. Updated scavenger hunt channel to broadcast user points.
- Add scavenger hunt points to map
=> Joins refactor

app/channels/scavenger_hunt_channel.rb, app/controllers/points_controller.rb, app/javascript/bundles/ScavengerHunt/components/NewScavengerHunt.jsx, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntForm.jsx, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/javascript/bundles/ScavengerHunt/services/scavengerHuntApi.js, app/javascript/bundles/ScavengerHunt/stores/ScavengerHuntStore.js, app/models/point.rb, app/models/user_point.rb, app/services/elastic_service.rb, app/views/scavenger_hunts/show.html.erb, app/views/user_scavenger_hunts/index.html.erb, lib/tasks/elastic_search_setup.rake, public/packs/manifest.json, spec/services/elastic_search_service_spec.rb
* Added user_points elasticsearch index
=> Joins table

app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/javascript/bundles/ScavengerHunt/markerStyle.js, public/packs/manifest.json
Add points within range to map. Add unique styling for points within/outside of range
=> Update point styling

app/controllers/current_scavenger_hunts_controller.rb, app/controllers/maps_controller.rb, app/models/scavenger_hunt.rb, app/services/scavengr_backend/user_scavenger_hunts.rb, app/views/current_scavenger_hunts/index.html.erb, app/views/home/index.html.erb, config/routes.rb
* Add find_or_create and index to current scavenger hunts service
* Add current scavenger hunts index
* Update maps controller to run find_or_create when scavenger hunt is started
=> Current hunts

Gemfile.lock, app/assets/stylesheets/scavenger-hunt-map.scss, app/javascript/bundles/ScavengerHunt/components/NewScavengerHunt.jsx, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntForm.jsx, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/javascript/bundles/ScavengerHunt/markerStyle.js, app/models/point.rb, app/models/user_point.rb, app/services/elastic_service.rb, app/services/scavengr_backend/user_scavenger_hunts.rb, app/views/scavenger_hunts/show.html.erb, lib/tasks/elastic_search_setup.rake, public/packs/manifest.json
* Add header and footer to scavenger hunt map page
* Update general styling on scavenger hunt map page
=> Map styling

app/assets/stylesheets/scavenger-hunt-map.scss, app/assets/stylesheets/user-scavenger-hunt.scss, app/views/user_scavenger_hunts/show.html.erb
* Update html
* Update styling
=> User scavenger hunt view

README.md
=> Minor revisions to readme

app/assets/javascripts/map_setup.js, app/javascript/bundles/ScavengerHunt/stores/ScavengerHuntStore.js, app/services/elastic_service.rb
* Update Done Adding Points button
* Speed up action cable request rate, and allow high accuracy location checking
* Reduce radius for within range points
=> Tracking speed

app/views/points/new.html.erb
=> Update add points page header

app/assets/stylesheets/scavenger-hunt-map.scss
* Adds z-index to footer on map page
=> Add z-index for footer

app/assets/stylesheets/dashboard.scss, app/assets/stylesheets/main.scss, app/assets/stylesheets/new-point-form.scss, app/assets/stylesheets/user-scavenger-hunt.scss, app/views/current_scavenger_hunts/index.html.erb, app/views/home/index.html.erb, app/views/points/new.html.erb, app/views/scavenger_hunts/edit.html.erb, app/views/scavenger_hunts/index.html.erb, app/views/scavenger_hunts/new.html.erb, app/views/scavenger_hunts/show.html.erb, app/views/user_scavenger_hunts/index.html.erb, app/views/user_scavenger_hunts/show.html.erb
* Removes footer logout button from all but dashboard. Removes dashboard footer button from dashboard.
* Centers footer button
* Adjust styling for new point view
* Add gradient styling to add points and done adding points buttons on new point view
* Make minor adjustments for consistency
=> Misc. styling

app/assets/javascripts/map_setup.js, app/assets/stylesheets/center-map-button.scss, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntForm.jsx, app/javascript/bundles/ScavengerHunt/components/ScavengerHuntMap.jsx, app/javascript/bundles/ScavengerHunt/stores/ScavengerHuntStore.js
* Add pin dropping feature to new points page
* Update location tracking in React to watchPosition and update more frequently
=> Location updates

app/assets/javascripts/map_setup.js
* Update new points map to center on user location
=> Add function to center new point map on user location

app/assets/javascripts/user_scavenger_hunt_show.js
* Fix incorrect div class name
=> Update div class name in user scavenger hunt show script

app/assets/javascripts/user_scavenger_hunt_show.js, app/views/user_scavenger_hunts/show.html.erb
=> Change points fetch request to request by scavenger hunt id

app/assets/javascripts/user_scavenger_hunt_show.js
* Add data to a tag in appended html
* Remove json parse call from point delete fetch request response
=> Changes to point fetch request
